
export const ALL_SPORTS = Array.from(new Set([
  "Marche", "Course à pied", "Course de haies", "Steeple", "Course à obstacles", "Course de relais", "Sprint", "Demi-fond", "Cross-country", "Marathon", "Trail", "Course en montagne", "Skyrunning", "Ultrafond", "Ultra-trail", "Lancer du disque", "Lancer du javelot", "Lancer du marteau", "Lancer du poids", "Saut en longueur", "Saut en hauteur", "Saut à la perche", "Triple saut", "Décathlon", "Heptathlon", "Pentathlon",
  "Arena football", "Balai-ballon sur glace", "Balle au tambourin", "Ballon au poing", "Bandy", "Baseball", "Basket-ball", "Basket-ball à trois", "Beach Handball", "Beach Volley", "Beach Soccer", "Beach Ultimate", "Bouzkachi", "Calcio florentin", "Camogie", "Cricket", "Crosse", "Crosse ancienne", "Cycle-ball", "Dodgeball", "Double Disc Court", "Fistball", "Flag football", "Floorball", "Foot à 5", "Football", "Football américain", "Football australien", "Football canadien", "Football gaélique", "Football de règles internationales", "Football universel", "Futsal", "Jorkyball", "Handball", "Hockey en salle", "Hockey subaquatique", "Hockey sur gazon", "Hockey sur glace", "Horse-ball", "Hurling", "Kabaddi", "Kayak-polo", "Kin-ball", "Korfbal", "Longue paume", "Moto-ball", "Netball", "Paintball", "Pelota P'urhépecha", "Pelote basque", "Pesäpallo", "Plumfoot", "Polo", "Rafroball", "Ringuette", "Rink hockey", "Roller derby", "Roller in line hockey", "Rollersoccer", "Rounders", "Rugby à sept", "Rugby à XV", "Rugby à XIII", "Sepak Takraw", "Shinty", "Slamball", "Softball", "Stoolball", "Street-hockey", "Tchoukball", "Touch rugby", "Town ball", "Ultimate", "Vigoro", "Volley-ball", "Volata", "Water-polo",
  "Bras de fer", "Bodybuilding", "Force basque", "Girevoy", "Haltérophilie", "Highland Games", "Powerlifting", "Tir à la corde",
  "WEC", "Karting", "NASCAR", "DTM", "WRC", "Formule 1", "Formule 2", "Formule 3", "Formule 4", "Formule E", "Course de côte", "Rallye-raid", "WTCC", "Indy Racing League", "Fol'Car", "Drift", "Autocross", "Rallycross", "Course de camions", "Dragster", "Endurance moto", "Enduro", "Freestyle motocross", "Motocross", "Supermotard", "Trial", "Speedway", "Stunt", "Supercross", "Vitesse moto", "Aéronautique", "Motonautisme", "Motoneige",
  "Badminton", "Beach tennis", "Jeu de paume", "Padel", "Peloc", "Racketlon", "Racquetball", "Soft tennis", "Speed Badminton", "Speed-ball", "Squash", "Tennis", "Tennis de table",
  "Agility", "Cani-cross", "Corrida", "Courses de lévriers", "Course de chameaux", "Course de chars", "Course de traîneaux", "Rodéo", "Sport hippique", "Amazone", "Attelage", "Concours complet", "Doma Vaquera", "Dressage", "Endurance", "Équitation Camargue", "Équitation islandaise", "Équitation Western", "Hunter", "Oulak", "Polocrosse", "Pony games", "Rodéo chilien", "Saut d'obstacles", "Ski joëring", "TREC", "Voltige en Cercle",
  "Barres", "Harpastum", "Jeu de mail", "Pancrace", "Pentathlon antique", "Pugilat", "Soule",
  "Aérobic", "Cheerleading", "Claquettes", "Corde à sauter", "Double dutch", "Cyclisme artistique", "Danse sportive", "Breakdance", "Fitness", "Gymnastique acrobatique", "Gymnastique aérobique", "Gymnastique artistique", "Gymnastique rythmique", "Parkour", "Trampoline", "Tumbling", "Majorette", "Natation synchronisée", "Patinage artistique", "Danse sur glace", "Patinage synchronisé", "Plongeon", "Pole dance", "Twirling bâton",
  "BMX", "BMX freestyle", "BMX Supercross", "Cyclisme sur piste", "Cyclisme sur route", "Ultracyclisme", "Cyclo-cross", "Cyclotourisme", "Vélo tout terrain",
  "Aïkibudo", "Aïkido", "Bando", "Banshay", "Capoeira", "Hapkido", "Jeet kune do", "Ju-jitsu", "Jiu-jitsu brésilien", "Judo", "Kalarippayatt", "Karaté", "Kendo", "Kobudo", "Krabi krabong", "Muay-boran", "Ninjutsu", "Sumo", "Taekwondo", "Tai-chi-chuan", "Unifight", "Viet vo dao", "Vovinam Việt Võ Đạo", "Wushu", "Wadō-ryū",
  "Boxe anglaise", "Boxe birmane", "Boxe française", "Boxe thaïlandaise", "Kick-boxing", "Canne et Bâton de combat", "Escrime", "Lutte gréco-romaine", "Lutte libre", "Lutte sénégalaise", "Mixed martial art (MMA)", "Krav-maga", "Sport chanbara",
  "Bobsleigh", "Curling", "Eisstock", "Luge", "Patinage de vitesse", "Short-track", "Skeleton",
  "Alpinisme", "Escalade", "Canyonisme", "Course d'orientation", "Spéléologie", "Randonnée pédestre", "Slackline",
  "Aéromodélisme", "Aérostation", "Base jump", "Cerf-volant", "Deltaplane", "Parachutisme", "Parapente", "ULM", "Vol libre", "Vol à voile", "Voltige aérienne",
  "Triathlon", "Duathlon", "Aquathlon", "Aquabike", "Pentathlon moderne", "Combiné nordique", "Biathlon", "Racketlon",
  "Airsoft", "Ball-trap", "Billard", "Boule bretonne", "Boule de fort", "Boulingrin", "Boomerang", "Bowling", "Croquet", "Fléchettes", "Golf", "Minigolf", "Pétanque", "Quilles de neuf", "Sarbacane sportive", "Sport boule", "Tir", "Tir à l'arc",
  "Aviron", "Bateau-dragon", "Canoë-kayak", "Chasse sous-marine", "Dragon Boat", "Motomarine", "Joutes nautiques", "Kayak-polo", "Kitesurf", "Nage avec palmes", "Nage en eau libre", "Nage en eau vive", "Planche à voile", "Plongée sous-marine", "Rafting", "Ski nautique", "Surf", "Voile", "Wakeboard", "Wakesurf",
  "Ski alpin", "Ski de randonnée", "Ski acrobatique", "Ski freestyle", "Ski freeride", "Ski de fond", "Ski de vitesse", "Ski extrême", "Ski télémark", "Bodyboard", "Mountainboard", "Roller", "Skateboard", "Snowboard", "Speed-riding", "Trottinette Freestyle",
  "Belote", "Bridge", "Dames", "Échecs", "Go", "Poker", "Scrabble", "Échecs chinois",
  "Air hockey", "Baby-foot", "Char à voile", "Culturisme", "Footbag", "Main à main", "Speedcubing", "Sport stacking", "Sport électronique", "Tricking", "Yoga"
]));
